apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: si-deployment
  name: si-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: si-deployment
  type: LoadBalancer
status:
  loadBalancer: {}
